# parser: ./lib/index.js
plugins:
  - coffee
  - prettier
extends:
  - eslint:recommended
  # - plugin:coffee/all
  - plugin:coffee/eslint-recommended
rules:
  no-undef: error
  coffee/prefer-destructuring: [error, {object: true}]
  prettier/prettier: [error, {parser: coffeescript, pluginSearchDirs: [.]}]
  use-isnan: error
  spaced-comment: [error, always, exceptions: ['-']]
  # no-warning-comments: error
  # capitalized-comments: error
  require-jsdoc: error
  prefer-rest-params: error
  # no-else-return: error
  # id-length: error
  # no-multi-assign: error
  no-self-compare: error
  no-console: error
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
  coffee/vars-on-top: off
  coffee/max-depth: off
  coffee/max-len: off
  coffee/complexity: off
  coffee/max-lines-per-function: off
env:
  node: true
  es6: true
  mocha: true
