# parser: ./lib/index.js
extends:
  - eslint:recommended
  - plugin:coffee/all
  - plugin:coffee/prettier
rules:
  coffee/prefer-destructuring: [error, {object: true}]
  require-jsdoc: error
  prefer-rest-params: error
  # no-else-return: error
  # id-length: error
  # no-multi-assign: error
  no-self-compare: error
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
  coffee/vars-on-top: off
  coffee/max-depth: off
  coffee/complexity: off
  coffee/max-lines-per-function: off
  coffee/capitalized-comments: off
  coffee/spaced-comment: off
  coffee/no-underscore-dangle: off
  coffee/no-commonjs: off
  coffee/valid-jsdoc: off
  coffee/multiline-comment-style: off
  coffee/no-return-assign: off
  # coffee/no-overwrite: [error, sameScope: false]
  coffee/block-scoped-var: off
  coffee/wrap-regex: off
  no-sparse-arrays: off
env:
  node: true
  es6: true
  mocha: true
