# parser: ./lib/index.js
plugins:
  - coffee
  - prettier
extends:
  - eslint:recommended
  - plugin:coffee/all
rules:
  no-undef: error
  coffee/prefer-destructuring: [error, {object: true}]
  prettier/prettier: [error, {parser: coffeescript, pluginSearchDirs: [.]}]
  require-jsdoc: error
  prefer-rest-params: error
  # no-else-return: error
  # id-length: error
  # no-multi-assign: error
  no-self-compare: error
  no-console: error
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
  coffee/vars-on-top: off
  coffee/max-depth: off
  coffee/max-len: off
  coffee/complexity: off
  coffee/max-lines-per-function: off
  coffee/capitalized-comments: off
  coffee/spaced-comment: off
  coffee/no-underscore-dangle: off
  coffee/no-commonjs: off
  coffee/valid-jsdoc: off
  coffee/multiline-comment-style: off
env:
  node: true
  es6: true
  mocha: true
