# parser: ./lib/index.js
extends:
  - plugin:coffee/all
  - plugin:coffee/prettier-run-as-rule
rules:
  coffee/prefer-destructuring: [error, {object: true}]
  coffee/no-unused-vars: [error, {varsIgnorePattern: ^_+$}]
  require-jsdoc: off
  prefer-rest-params: error
  # no-else-return: error
  # id-length: error
  # no-multi-assign: error
  no-self-compare: error
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
  coffee/vars-on-top: off
  coffee/max-depth: off
  coffee/complexity: off
  coffee/max-lines-per-function: off
  coffee/capitalized-comments: off
  coffee/spaced-comment: off
  coffee/no-underscore-dangle: off
  coffee/no-commonjs: off
  coffee/valid-jsdoc: off
  coffee/multiline-comment-style: off
  coffee/no-return-assign: off
  # coffee/no-overwrite: [error, sameScope: false]
  coffee/block-scoped-var: off
  coffee/wrap-regex: off
  no-sparse-arrays: off
  coffee/no-cond-assign: off
  coffee/spread-direction: off
  sort-keys: off
  global-require: off
  max-lines: off
  require-unicode-regexp: off
  no-inline-comments: off
  line-comment-position: off
  max-statements: off
  coffee/id-length: off
  no-plusplus: off
  no-param-reassign: off
  no-continue: off
  default-case: off
  no-warning-comments: off
  max-params: off
  no-sync: off
  no-multi-assign: off
  no-bitwise: off
  coffee/dot-location: off
  max-classes-per-file: off
  sort-imports: off
  coffee/lines-between-class-members: off
  coffee/guard-for-in: off
  callback-return: off
  coffee/no-use-before-define: off
  coffee/prefer-object-spread: off
  coffee/no-nested-interpolation: off
  coffee/class-methods-use-this: off
  no-process-env: off
env:
  node: true
  es6: true
  mocha: true
